FROM bench-image

RUN eval `opam config env` && \
    ./configure && \
    make -j2

USER root

RUN make install
RUN sudo adduser --disabled-password --gecos '' guest
USER guest
ENV HOME /home/guest
WORKDIR /home/guest

RUN why3 config --detect

