include:
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest
    inputs:
      stage: check

workflow:
  rules:
    # Conditions for running a pipeline automatically.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true") || $CI_PIPELINE_SOURCE == "schedule"
      when: always
    # Also run a pipeline when "Run pipeline" is selected in the GitLab UI
    # from the project’s "Build > Pipelines" section.
    - if: $CI_PIPELINE_SOURCE == "web"
    # Don't run a pipeline on any other events.
    - when: never

stages:
  - build
  - check

.common_test:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
  script:
    # Use generic_anod_ci here.
    - generic_anod_ci $GENERIC_ANOD_CI_OPTIONS
    - cat /tmp/ci_env.sh
    - . /tmp/ci_env.sh
    # Go to the sandbox dir
    - cd $ANOD_DEFAULT_SANDBOX_DIR
    - anod build why3 --latest

linux:
  extends: .common_test
  services:
    - image:pe-base
    - cpu:8

windows:
  extends: .common_test
  services:
    - image:e3-windows-2022
    - platform:x86_64-windows-2022
    - cpu:2
    - mem:4
    - disk:100
