(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import ZArith.
Require Import Rbase.
Require Import Rfunctions.
Require real.Real.
Require int.Int.

Axiom Power_s : forall (x:R) (n:Z), (0%Z <= n)%Z ->
  ((powerRZ x (n + 1%Z)%Z) = (x * (powerRZ x n))%R).

Axiom Power_sum : forall (x:R) (n:Z) (m:Z), ((0%Z <= n)%Z /\ (0%Z <= m)%Z) ->
  ((powerRZ x (n + m)%Z) = ((powerRZ x n) * (powerRZ x m))%R).

Axiom Power_mult : forall (x:R) (n:Z) (m:Z), (0%Z <= n)%Z -> ((0%Z <= m)%Z ->
  ((powerRZ x (n * m)%Z) = (powerRZ (powerRZ x n) m))).

Require Import Interval_tactic.

(* Why3 goal *)
Theorem pow_eps2_max_int : ((powerRZ (1%R + ((7 / 1125899906842624)%R + (3 / 9007199254740992)%R)%R)%R 2147483647%Z) <= 2%R)%R.
Strategy 1000 [powerRZ].
interval with (i_prec 34).
Qed.

