(* This file is generated by Why3's Coq 8.4 driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Power.

Require Import Interval_tactic.

(* Why3 goal *)
Theorem g : ((int.Power.power 2%Z 3321941%Z) < (int.Power.power 10%Z
  ((int.Power.power 10%Z 6%Z) + 4%Z)%Z))%Z /\ ((int.Power.power 10%Z
  ((int.Power.power 10%Z 6%Z) + 4%Z)%Z) < (int.Power.power 2%Z 3321942%Z))%Z.
interval.

Qed.

