\begin{syntax}
  lqualid ::= (uident ".")* lident
  \
  uqualid ::= (uident ".")* uident
  \
  qualid ::= (uident ".")* (lident-ext | uident)
  \
  lident-ext ::= lident | "(" lident-op ")"
  \
  lident-op ::= op-char-1234+     ;   infix or bang operator
              | op-char-1234+ "_" ;   prefix (non-bang) operator
              | "[]"              ;   collection access
              | "[<-]"            ;   collection update
              | "[]<-"            ;   in-place collection update
              | "[..]"            ;   collection slice
              | "[_..]"           ;   right-open slice
              | "[.._]"           ;   left-open slice %
\end{syntax}
