\begin{syntax}
  lalpha ::= "a"-"z" | "_"
  \
  ualpha ::= "A"-"Z"
  \
  digit-or-us ::= "0"-"9" | "_"
  \
  alpha-no-us ::= "a"-"z" | "A"-"Z"
  \
  suffix ::= (alpha-no-us | "'"* digit-or-us)* "\"*
  \
  lident-nq ::= lalpha suffix
  \
  uident-nq ::= ualpha suffix
  \
  lident ::= lident ("'" alpha-no-us suffix)+
  \
  uident ::= uident ("'" alpha-no-us suffix)+
  \
  ident-nq ::= lident-nq | uident-nq
  \
  ident ::= lident | uident
  \
  lqualid ::= lident | uqualid "." lident
  \
  uqualid ::= uident | uqualid "." uident
  \
  qualid ::= ident | uqualid "." ident ;%
\end{syntax}
