\begin{syntax}
  type-v ::= type
       | "(" type-v ")"        ; parentheses
       | type-v "->" type-c    ;
       | type-v-binder "->" type-c
  \
  type-v-binder ::= lident label* ":" type-v
  \
  type-v-param ::= "(" type-v-binder ")"
  \
  type-c ::= type-v ;
    | pre type-v effect post
  \
  effect ::= reads? writes? raises?
  \
  reads ::= "reads" tr-term+
  \
  writes ::= "writes" tr-term+
  \
  raises ::= "raises" uqualid+
  \
  pre ::= annotation
  \
  post ::= annotation post-exn*
  \
  post-exn ::= "|" uqualid "->" annotation
  \
  annotation ::= "{}"  | "{" formula "}"
  \
\end{syntax}