\begin{syntax}
  type ::= lqualid type*     ; type symbol
       | "'" lident          ; type variable
       | "(" ("," type)* ")" ; tuple type
       | "(" type ")"        ; parentheses %
\end{syntax}