\begin{syntax}
  type ::= lqualid type*     ; type symbol
       | "'" lident          ; type variable
       | type "->" type      ; mapping type
       | "()"		     ; unit type
       | "(" type ("," type)+ ")" ; tuple type
       | "{" type "}"        ; snapshot type
       | "(" type ")"        ; parentheses %
\end{syntax}
