.TH why 1 "February, 2010"

.SH NAME
why \- A language for program verification


.SH SYNOPSIS
.B why
[
.B options
]
.B files


.SH DESCRIPTION

.B why
is a verification tool. 
It takes annotated programs as input 
and outputs verification conditions for several proof assistants (Coq,
PVS, Isabelle/HOL, etc.) and decision procedures (Alt-Ergo, Simplify,
Z3, etc.).

.SH OPTIONS

.TP
.B \-h
Help. Will give you the full list of command line options.


.SH CONTACT
.I Jean-Christophe Filliatre <filliatr@lri.fr>


.SH SEE ALSO

.I
Why web site: http://why.lri.fr/

