
(*
#load "unix.cma"
#directory "../util"
#load "sysutil.cmo"
*)

open Format

let gen_dir fmt d suffix =
  let dir = "." ^ d in
  let t = Sys.readdir dir in
  for i = 0 to Array.length t - 1 do
    let file = t.(i) in
    let f = Filename.concat dir file in
    if Filename.check_suffix f suffix then
      let c = String.escaped (Sysutil.file_contents f) in
      fprintf fmt "\"%s/%s\",@\n\"%s@\n\";@\n" d file c
  done

let () =
  let ch = open_out "src/trywhy3/theories.ml" in
  let fmt = formatter_of_out_channel ch in
  fprintf fmt "(* generated by gen_theories.ml *)@\n@\n";
  fprintf fmt "let theories = [@\n";
  gen_dir fmt "/theories" ".why";
  gen_dir fmt "/modules" ".mlw";
  gen_dir fmt "/modules/mach" ".mlw";
  fprintf fmt "]@\n";
  close_out ch
