
WHY3=moloch:/users/www-perso/projets/why3

install-help-microc:
	scp help_micro-C.html $(WHY3)/micro-C/trywhy3_help.html
	scp trywhy3_help.css $(WHY3)/micro-C/

install-help-python:
	scp help_python.html $(WHY3)/python/trywhy3_help.html
	scp trywhy3_help.css $(WHY3)/python/
