
WHY3=moloch:/users/www-perso/projets/why3

install-help-microc:
	scp help_microc.html $(WHY3)/microC/trywhy3_help.html
	scp trywhy3_help.css $(WHY3)/microC/

install-help-python:
	scp help_python.html $(WHY3)/python/trywhy3_help.html
	scp trywhy3_help.css $(WHY3)/python/
