(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require set.Set.

(* Why3 assumption *)
Definition rel (a:Type) {a_WT:WhyType a} (b:Type) {b_WT:WhyType b} :=
  (set.Set.set (a* b)%type).


