(********************************************************************)
(*                                                                  *)
(*  The Why3 Verification Platform   /   The Why3 Development Team  *)
(*  Copyright 2010-2018   --   Inria - CNRS - Paris-Sud University  *)
(*                                                                  *)
(*  This software is distributed under the terms of the GNU Lesser  *)
(*  General Public License version 2.1, with the special exception  *)
(*  on linking described in file LICENSE.                           *)
(*                                                                  *)
(********************************************************************)

(* Debugging function *)
val print_table:
    Smt2_model_defs.correspondence_table -> unit

(* From the table generated by the parser, build a list of model_element *)
val create_list:
    Smt2_model_defs.correspondence_table -> Model_parser.model_element list
