(**************************************************************************)
(*                                                                        *)
(*  The J3 plugin for TrustInSoft Analyzer                                *)
(*  Copyright 2019-2022   --   Inria - Université Paris-Saclay            *)
(*    Copyright (C) 2022-2023 TrustInSoft                                 *)
(*                                                                        *)
(*  This software is distributed under the terms of the GNU Lesser        *)
(*  General Public License version 2.1, with the special exception        *)
(*  on linking described in file LICENSE.                                 *)
(*                                                                        *)
(**************************************************************************)
