(* This file is generated by Why3's Coq 8.4 driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require Import ZOdiv.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require int.ComputerDivision.
Require number.Parity.
Require number.Divisibility.
Require number.Gcd.

(* Why3 assumption *)
Definition unit := unit.

(* Why3 goal *)
Theorem WP_parameter_euclid : forall (u:Z) (v:Z), ((0%Z <= u)%Z /\
  (0%Z <= v)%Z) -> ((~ (v = 0%Z)) -> let o := (ZOmod u v) in
  (((0%Z <= v)%Z /\ (0%Z <= o)%Z) -> ((number.Gcd.gcd v
  o) = (number.Gcd.gcd u v)))).
Proof.
intuition.
symmetry.
rewrite Gcd.Comm.
rewrite Gcd.gcd_euclid with (q:=(ZOdiv u v)).
apply f_equal.
rewrite (ZO_div_mod_eq u v) at 1.
ring.
Qed.

