name: Main workflow

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-22.04
          - windows-2019
          - ubuntu-22.04-arm
        ocaml-compiler:
          - "4.13.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Call build script
        run: |
          opam exec -- bash ./fsf_build.sh staging

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: why3pack-${{matrix.os}}
          path: staging
