name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Setup OCaml v2 ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: opam install depext
        run: opam depext camlzip zarith re seq why3

      - run: opam install camlzip dune dune-configurator menhir num ocamlgraph re seq yojson zarith

      - run: opam exec -- bash configure --prefix=/tmp/why3install --enable-relocation --disable-emacs-compilation --disable-hypothesis-selection --disable-js-of-ocaml
      - run: opam exec -- make
      - run: opam exec -- make install_spark2014

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: why3_${{matrix.os}}
          path: /tmp/why3install
